// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: batch.go

package db

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const updateProductPrice = `-- name: UpdateProductPrice :batchexec
UPDATE partner_stockrecord SET price = $3::pg_catalog.numeric, date_updated = now() WHERE partner_id = $1 AND partner_sku = $2
`

type UpdateProductPriceBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpdateProductPriceParams struct {
	PartnerID  int64
	PartnerSku string
	Price      float64
}

// Update products from the values in the item_preco table
func (q *Queries) UpdateProductPrice(ctx context.Context, arg []UpdateProductPriceParams) *UpdateProductPriceBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.PartnerID,
			a.PartnerSku,
			a.Price,
		}
		batch.Queue(updateProductPrice, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpdateProductPriceBatchResults{br, len(arg), false}
}

func (b *UpdateProductPriceBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpdateProductPriceBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
