// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PartnerStockrecord struct {
	ID                int64
	PartnerSku        string
	PriceCurrency     string
	Price             pgtype.Numeric
	NumInStock        pgtype.Int4
	NumAllocated      pgtype.Int4
	LowStockThreshold pgtype.Int4
	DateCreated       pgtype.Timestamptz
	DateUpdated       pgtype.Timestamptz
	PartnerID         int64
	ProductID         int64
}
