// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ItemPreco struct {
	CodigoItem          float64
	CodigoUnidade       int
	CodigoPrazo         int
	CodigoComissao      pgtype.Int4
	Preco               float64
	PermiteDesconto     int
	DescontoMaximo      float64
	AlteracaoPreco      pgtype.Date
	DescontoMaximoProg  float64
	DebitoEmpresaProg   float64
	CreditoVendedorProg float64
	DebitoVendedorProg  float64
	NumeroAlteracao     int
	FlagDelivery        int
}

type VnLastNotificationEvent struct {
	EventType  string
	CodigoItem float64
	DateSent   pgtype.Timestamptz
}

type VnPriceUpdateWatcher struct {
	LastUpdate pgtype.Timestamptz
	PricesHash string
}
