// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ItemPreco struct {
	CodigoItem          float64
	CodigoUnidade       int32
	CodigoPrazo         int32
	CodigoComissao      pgtype.Int4
	Preco               pgtype.Numeric
	PermiteDesconto     int32
	DescontoMaximo      pgtype.Numeric
	AlteracaoPreco      pgtype.Date
	DescontoMaximoProg  pgtype.Numeric
	DebitoEmpresaProg   pgtype.Numeric
	CreditoVendedorProg pgtype.Numeric
	DebitoVendedorProg  pgtype.Numeric
	NumeroAlteracao     int32
	FlagDelivery        int32
}

type VnLastNotificationEvent struct {
	EventType  string
	CodigoItem float64
	DateSent   pgtype.Timestamptz
}

type VnPriceUpdateWatcher struct {
	LastUpdate pgtype.Timestamptz
	PricesHash string
}
